version: 2.1
executors:
  mypublisher:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      PROJECT_NAME: project1-team-6

jobs:
  build:
    executor: mypublisher
    steps:
      - checkout
      - setup_remote_docker
      # - run:
      #     name: Build Docker images
      #     command: docker-compose -f ./docker-compose.prod.yml build --compress --force-rm --no-cache --pull --parallel
      - run:
          name: Build Docker images
          command: docker build -f Dockerfile.prod -t nodeapi .
      - run:
          name: Save Docker image
          command: docker save -o ./${PROJECT_NAME}.tar nodeapi
      - persist_to_workspace:
          root: .
          paths:
            - ./*.tar

  publish:
    executor: mypublisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load saved nodejs image
          command: docker load -i /tmp/workspace/${PROJECT_NAME}.tar
      - run:
          name: Rename nodejs image
          command: docker tag nodeapi ${DH_USERNAME}/${PROJECT_NAME}:latest
      - run:
          name: Login to Docker Hub
          command: docker login -u ${DH_USERNAME} --password ${DH_PASS}
      - run:
          name: Publish the Image
          command: docker push ${DH_USERNAME}/${PROJECT_NAME}:latest

workflows:
  version: 2.1
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
